### ISSUE TITLE
Statistics GUI causes server crash

### ISSUE THREAD

**Issue by HermanBergner** [HermanBergner/factorio_scenario#2]
If you have another element open, and open / close the statistics GUI, the game can crash

**Comment by HermanBergner** [comment]
<img width="356" alt="screen shot 2017-08-13 at 22 21 33" src="https://user-images.githubusercontent.com/9516673/29253123-d0973678-8075-11e7-9d7b-90e70fa70fed.png">

**Comment by Wouyoshi** [comment]
Fixed the issue
